### ISSUE TITLE
Security risks

### ISSUE THREAD

**Issue by cauyxy** [Mr-strlen/ZhouJiTalentManagementSystem#5]
Put the database Account-Password into config.py and add .gitignore.

**Comment by Mr-strlen** [comment]
Thanks, I have deleted it

**Comment by xyqlx** [comment]
This is not the correct way to remove sensitive data from a repository, and now I can still see it in commit history.

<https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository>

**Comment by Mr-strlen** [comment]
Thank you for reminding and informing me. I have reset the server now. I will pay attention not to upload sensitive information to GitHub. Thanks a lot.
